"""This file was generated by xsdata, v24.7, on 2024-07-31 11:16:27

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from enum import Enum
from typing import Dict, Optional, Tuple, Union

from pydantic import BaseModel, ConfigDict
from xsdata.models.datatype import XmlDateTime
from xsdata_pydantic.fields import field

from greenbutton_objects.data.atom.xml import LangValue

__NAMESPACE__ = "http://www.w3.org/2005/Atom"


class TextTypeType(Enum):
    TEXT = "text"
    HTML = "html"
    XHTML = "xhtml"


class CategoryType(BaseModel):
    """
    The Atom cagegory construct is defined in section 4.2.2 of the format spec.
    """

    class Meta:
        name = "categoryType"

    model_config = ConfigDict(defer_build=True)
    term: str = field(
        metadata={
            "type": "Attribute",
            "required": True,
        }
    )
    scheme: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    label: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class ContentType(BaseModel):
    """
    The Atom content construct is defined in section 4.1.3 of the format spec.
    """

    class Meta:
        name = "contentType"

    model_config = ConfigDict(defer_build=True)
    type_value: Optional[str] = field(
        default=None,
        metadata={
            "name": "type",
            "type": "Attribute",
        },
    )
    src: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )
    content: Tuple[object, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )


class DateTimeType(BaseModel):
    class Meta:
        name = "dateTimeType"

    model_config = ConfigDict(defer_build=True)
    value: XmlDateTime = field(
        metadata={
            "required": True,
        }
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class GeneratorType(BaseModel):
    """
    The Atom generator element is defined in section 4.2.4 of the format spec.
    """

    class Meta:
        name = "generatorType"

    model_config = ConfigDict(defer_build=True)
    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    uri: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    version: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class IconType(BaseModel):
    """
    The Atom icon construct is defined in section 4.2.5 of the format spec.
    """

    class Meta:
        name = "iconType"

    model_config = ConfigDict(defer_build=True)
    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class IdType(BaseModel):
    """
    The Atom id construct is defined in section 4.2.6 of the format spec.
    """

    class Meta:
        name = "idType"

    model_config = ConfigDict(defer_build=True)
    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class LinkType(BaseModel):
    """
    The Atom link construct is defined in section 3.4 of the format spec.
    """

    class Meta:
        name = "linkType"

    model_config = ConfigDict(defer_build=True)
    href: str = field(
        metadata={
            "type": "Attribute",
            "required": True,
        }
    )
    rel: str = field(
        metadata={
            "type": "Attribute",
            "required": True,
        }
    )
    type_value: Optional[str] = field(
        default=None,
        metadata={
            "name": "type",
            "type": "Attribute",
        },
    )
    hreflang: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    title: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    length: Optional[int] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )
    content: Tuple[object, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )


class LogoType(BaseModel):
    """
    The Atom logo construct is defined in section 4.2.8 of the format spec.
    """

    class Meta:
        name = "logoType"

    model_config = ConfigDict(defer_build=True)
    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class TextType(BaseModel):
    """
    The Atom text construct is defined in section 3.1 of the format spec.
    """

    class Meta:
        name = "textType"

    model_config = ConfigDict(defer_build=True)
    type_value: Optional[TextTypeType] = field(
        default=None,
        metadata={
            "name": "type",
            "type": "Attribute",
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )
    content: Tuple[object, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )


class UriType(BaseModel):
    class Meta:
        name = "uriType"

    model_config = ConfigDict(defer_build=True)
    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class PersonType(BaseModel):
    """
    The Atom person construct is defined in section 3.2 of the format spec.
    """

    class Meta:
        name = "personType"

    model_config = ConfigDict(defer_build=True)
    name: Tuple[str, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    uri: Tuple[UriType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    email: Tuple[str, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
            "pattern": r"\w+@(\w+\.)+\w+",
        },
    )
    other_element: Tuple[object, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Wildcard",
            "namespace": "##other",
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class EntryType(BaseModel):
    """
    The Atom entry construct is defined in section 4.1.2 of the format spec.
    """

    class Meta:
        name = "entryType"

    model_config = ConfigDict(defer_build=True)
    author: Tuple[PersonType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    category: Tuple[CategoryType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    content: Tuple[ContentType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    contributor: Tuple[PersonType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    id: Tuple[IdType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    link: Tuple[LinkType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    published: Tuple[DateTimeType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    rights: Tuple[TextType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    source: Tuple[TextType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    summary: Tuple[TextType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    title: Tuple[TextType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    updated: Tuple[DateTimeType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    other_element: Tuple[object, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Wildcard",
            "namespace": "##other",
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class SourceType(BaseModel):
    """
    The Atom source construct is defined in section 4.2.11 of the format spec.
    """

    class Meta:
        name = "sourceType"

    model_config = ConfigDict(defer_build=True)
    author: Tuple[PersonType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    category: Tuple[CategoryType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    contributor: Tuple[PersonType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    generator: Tuple[GeneratorType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    icon: Tuple[IconType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    id: Tuple[IdType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    link: Tuple[LinkType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    logo: Tuple[LogoType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    rights: Tuple[TextType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    subtitle: Tuple[TextType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    title: Tuple[TextType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    updated: Tuple[DateTimeType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    other_element: Tuple[object, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Wildcard",
            "namespace": "##other",
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class Entry(EntryType):
    class Meta:
        name = "entry"
        namespace = "http://www.w3.org/2005/Atom"

    model_config = ConfigDict(defer_build=True)


class FeedType(BaseModel):
    """
    The Atom feed construct is defined in section 4.1.1 of the format spec.
    """

    class Meta:
        name = "feedType"

    model_config = ConfigDict(defer_build=True)
    author: Tuple[PersonType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    category: Tuple[CategoryType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    contributor: Tuple[PersonType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    generator: Tuple[GeneratorType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    icon: Tuple[IconType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    id: Tuple[IdType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
            "min_occurs": 3,
        },
    )
    link: Tuple[LinkType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    logo: Tuple[LogoType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    rights: Tuple[TextType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    subtitle: Tuple[TextType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    title: Tuple[TextType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
            "min_occurs": 3,
        },
    )
    updated: Tuple[DateTimeType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
            "min_occurs": 3,
        },
    )
    entry: Tuple[EntryType, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Element",
            "namespace": "http://www.w3.org/2005/Atom",
        },
    )
    other_element: Tuple[object, ...] = field(
        default_factory=tuple,
        metadata={
            "type": "Wildcard",
            "namespace": "##other",
        },
    )
    base: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    lang: Optional[Union[str, LangValue]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )
    other_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##other",
        },
    )


class Feed(FeedType):
    class Meta:
        name = "feed"
        namespace = "http://www.w3.org/2005/Atom"

    model_config = ConfigDict(defer_build=True)
