"""This file was generated by xsdata, v24.7, on 2024-08-08 14:41:00

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from enum import Enum

__NAMESPACE__ = "http://www.w3.org/XML/1998/namespace"


class LangValue(Enum):
    VALUE = ""
