"""This file was generated by xsdata, v24.7, on 2024-07-31 11:14:52

Generator: PydanticGenerator
See: https://xsdata.readthedocs.io/
"""

from enum import Enum

__NAMESPACE__ = "http://www.w3.org/XML/1998/namespace"


class LangValue(Enum):
    VALUE = ""
