repos:

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.12.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
        - id: actionlint

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.27.3
    hooks:
        - id: check-github-actions
        - id: check-github-workflows
        - id: check-readthedocs

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
        stages: ["pre-commit"]

  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        exclude: src/greenbutton_objects/data
      - id: ruff-format
        exclude: src/greenbutton_objects/data

  - repo: https://github.com/lsst-ts/pre-commit-xmllint
    rev: v1.0.0
    hooks:
      - id: format-xmllint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        types: [python]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
        stages:
          - pre-push
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
